#pragma once

#include "nanoxgen/types.h"
#include "nanoxgen/xgen_classic.h"
#include "nanoxgen/xgen_classic_alembic.h"

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <span>
#include <string_view>
#include <vector>

namespace nanoxgen {

struct ClassicRootGenerationLimits {
    std::uint64_t max_candidates{100000000u};
    std::uint64_t max_roots{100000000u};
};

struct ClassicRootFaceStats {
    std::uint32_t face_id{};
    std::uint32_t candidate_count{};
    std::uint32_t mask_accepted_count{};
    std::uint32_t root_count{};
};

struct ClassicGuideInfluence {
    std::uint32_t guide_index{};
    float weight{};
};

struct ClassicRootPlan {
    std::vector<RootSample> roots;
    // Reference-pose global position used by Classic's $Prefg expression
    // variable. This remains separate from the current renderer root.
    std::vector<Vec3> reference_positions;
    // Current-pose XGen cU frame direction used by authored FX modules.
    std::vector<Vec3> surface_tangents;
    // XGen resets the renderer primitive ID for every patch face and counts
    // RandomGenerator candidates from one. Rejected mask samples therefore
    // leave observable gaps in later $id expressions.
    std::vector<std::uint32_t> primitive_ids;
    // SeExpr hash state after exact double (u,v,faceSeed) ingestion. Runtime
    // rand() appends its call-site/explicit seed using uint arithmetic only.
    std::vector<std::uint32_t> random_prefixes;
    // CSR guide association generated by XGen's directional support test.
    // Empty means that the imported guides did not carry Classic support
    // metadata; otherwise this contains roots.size() + 1 entries.
    std::vector<std::uint32_t> influence_offsets;
    std::vector<ClassicGuideInfluence> influences;
    std::vector<std::filesystem::path> ptex_maps;
    std::vector<ClassicRootFaceStats> face_stats;
    std::uint64_t candidate_count{};
    std::uint64_t mask_rejected_count{};
    std::uint64_t patch_culled_count{};
    std::uint64_t guide_rejected_count{};
};

struct ClassicExplicitRoot {
    std::uint32_t face_id{};
    Vec2 uv{};
    Vec3 position{};
    std::uint32_t primitive_id{};
};

// Raw XGen guide-association weight before normalization. Exposed for
// calibration/differential tests; production callers normally use the root
// planner, which rejects samples whose complete guide-weight sum is empty.
[[nodiscard]] float evaluate_xgen_classic_guide_weight(
    const GuideInput &guide, Vec3 reference_position,
    Vec3 reference_normal) noexcept;

[[nodiscard]] float evaluate_xgen_classic_random_mask(
    const ClassicDescription &description,
    const std::filesystem::path &description_directory,
    std::string_view patch_name, std::uint32_t face_id,
    float u, float v);

// Evaluate RandomGenerator density and mask against imported coarse faces.
// description_directory is the concrete expansion of ${DESC}; PTEX is decoded
// before GPU execution and roots retain stable (faceId,u,v) identities.
[[nodiscard]] ClassicRootPlan build_xgen_classic_random_root_plan(
    const ClassicDescription &description,
    const ClassicAlembicAssetInput &surface,
    const std::filesystem::path &description_directory,
    const ClassicRootGenerationLimits &limits = {});

// Associate caller-provided patch locations with the description's authored
// guides. XPD clump points retain face/u/v identity and face-local primitive
// IDs; their cached authoring-position xyz is validated, while the evaluated
// root is sampled from the current render patch.
[[nodiscard]] ClassicRootPlan build_xgen_classic_explicit_root_plan(
    const ClassicDescription &description,
    const ClassicAlembicAssetInput &surface,
    std::string_view patch_name,
    std::span<const ClassicExplicitRoot> samples);

// Rebuild each authored guide using XGen's uniform SgCurve convention, then
// blend guide offsets with the exact associations retained by the root plan.
// The final renderer payload remains float4(position, radius); double is used
// only for the host-side SgCurve-compatible intermediate arithmetic.
[[nodiscard]] PackedGeneratedCurves generate_xgen_classic_base_curves_cpu(
    const AssetBuildInput &asset,
    const ClassicRootPlan &roots,
    std::uint32_t cvs_per_strand,
    float diameter = 0.0f,
    float radius_scale = 1.0f);

// Flatten XGen's uniformly rebuilt guide CVs as guide-major float3 data for
// renderer/GPU upload. Rebuilding is a one-time host operation; device kernels
// consume only float data and never require FP64 support.
[[nodiscard]] std::vector<Vec3> rebuild_xgen_classic_guides_for_device(
    const AssetBuildInput &asset,
    std::uint32_t cvs_per_guide);

} // namespace nanoxgen
